In [1]:
import sklearn

In [4]:
from sklearn import datasets

In [6]:
iris = datasets.load_iris()

In [8]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn import svm

In [13]:
clasificador = svm.SVC(gamma=0.001, C=100.0)

In [16]:
clasificador.fit(X=iris.data, y=iris.target)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [17]:
clasificador.predict(iris.data)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
digits = datasets.load_digits()

In [19]:
clasificador2 = svm.SVC(gamma=0.001, C=100.0)

In [20]:
clasificador2.fit(X=digits.data, y=digits.target)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [21]:
clasificador2.predict(digits.data)

array([0, 1, 2, ..., 8, 9, 8])

In [22]:
import numpy as np

In [24]:
np.sum(clasificador2.predict(digits.data) == digits.target)

1797

In [25]:
np.sum(clasificador2.predict(digits.data) != digits.target)

0

In [26]:
import pickle

In [27]:
open?

In [37]:
#Escribir el modelo
pickle.dump(clasificador2,open('pp', mode='wb'))

In [33]:
ls

01_intro_jupiter.ipynb
02-loading_and_saving_data_2018_04_14-clean.ipynb
03-merge_concatenate_transform-clean.ipynb
03-notebook.ipynb
04-data-aggregation.ipynb
04-group_by_AAF.ipynb
05-visualitation.ipynb
05-visualization_introduction_AAF.ipynb
06-intro_to_pandas_practical_AAF.ipynb
06-pandas-practical.ipynb
201712_detalle.csv
207831-0-accidentes-trafico.xls
207831-0-accidentes-trafico.xls.1
210104-180-multas-circulacion-detalle.csv
914310910_T_T100_SEGMENT_ALL_CARRIER_2015_All.csv
914310910_T_T100_SEGMENT_ALL_CARRIER_ReadMe.csv
914310910_T_T100_SEGMENT_ALL_CARRIER_Terms.csv
accidentes.xls
anaconda3/
bash_history
Data/
derby.log
Desktop/
Documents/
Downloads/
example.db
fashion.R
first_dir/
Introduccion a R.ipynb
metastore_db/
modelo_cnn_base.h5
multas.csv
Music/
my_fb_friends.csv
mystyles.py
nmist_cnn.R
one/
On_Time_On_Time_Performance_2015_1.csv
Pictures/
pp
pp.txt
Public/
__pycache__/
R/
readme.html
Repos/
R-Notebooks/
size.txt
sklearn1.ipynb
Templates/
tensorflow.R
tips.csv
uniq_ex

In [34]:
! ls -l

total 408860
-rw-r--r--  1 dsc dsc    105259 ene 12 09:34 01_intro_jupiter.ipynb
-rw-r--r--  1 dsc dsc    865323 ene 12 13:35 02-loading_and_saving_data_2018_04_14-clean.ipynb
-rw-r--r--  1 dsc dsc     14028 ene 18 17:20 03-merge_concatenate_transform-clean.ipynb
-rw-r--r--  1 dsc dsc     97301 ene 18 19:13 03-notebook.ipynb
-rw-r--r--  1 dsc dsc     91077 ene 18 21:47 04-data-aggregation.ipynb
-rw-r--r--  1 dsc dsc     77912 ene 18 17:06 04-group_by_AAF.ipynb
-rw-r--r--  1 dsc dsc    249156 ene 19 11:29 05-visualitation.ipynb
-rw-r--r--  1 dsc dsc    617076 ene 19 12:09 05-visualization_introduction_AAF.ipynb
-rw-r--r--  1 dsc dsc    546843 ene 18 17:07 06-intro_to_pandas_practical_AAF.ipynb
-rw-r--r--  1 dsc dsc    234790 ene 19 13:59 06-pandas-practical.ipynb
-r--------  1 dsc dsc  53252030 ene 12 10:48 201712_detalle.csv
-rw-r--r--  1 dsc dsc     61952 feb 17  2017 207831-0-accidentes-trafico.xls
-rw-r--r--  1 dsc dsc     61952 feb 17  2017 207831-0-accidentes-trafico.xls.1
-rw-r--

In [36]:
# cargar el modelo
pickle.load(open("pp", "rb"))

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [40]:
import joblib #otra libreria que hace lo mismo que pickle mas rapida

In [39]:
! pip install joblib

    100% |████████████████████████████████| 286kB 2.2MB/s ta 0:00:01
You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [42]:
joblib.dump(clasificador2, "clasificador2")

['clasificador2']

In [43]:
joblib.load( "clasificador2")

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [44]:
clasificador2.gamma

0.001

## KNN

In [47]:
import numpy as np

In [48]:
iris

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [49]:
iris.data.shape

(150, 4)

In [51]:
# desordenamos para crear el training y test
np.random.permutation(150)

array([ 73, 126, 125,  67,  37, 143, 149, 141,  96,  61,  45, 128,  59,
       145, 118, 117,  57, 120,  19,  44,  60, 109,  71,  82,  39,  48,
        81,  62, 124,  66, 144,  25,  50,  23,  89,  94,  58,  83,   5,
        36, 107,  28,  68,  18,  10,  72,  80, 129, 108,  42, 112,   1,
        91,  53, 114, 100,  75,  63,  65, 104,  84, 133, 132, 135,  88,
        11,  26, 138,  14,   3,   4,  95,  99, 137,  51,  29,  79, 106,
        38,  13, 130, 136,  21,  33, 122,  74, 140, 134,  52,  70, 101,
         7,   9, 131, 103, 121, 139,  92,  90,  76,  47,  43,  98,  49,
        46, 110,  35,  34,  41,  85, 146, 116,  12,  17, 127, 115,   2,
        31, 123,  20,  30,  56, 105,  24,  93,  55,   0,  27, 147,  54,
        86,  69,  78, 113,  97,  64, 119,  22, 102, 148,  15,   8,  40,
       111,  32,  16, 142,  77,  87,   6])

In [52]:
idx = np.random.permutation(150)

In [65]:
iris_X_train = iris.data[idx[:-20]]
iris_y_train = iris.target[idx[:-20]]
iris_X_test = iris.data[idx[-20:]]
iris_y_test = iris.target[idx[-20:]]

In [62]:
knn = sklearn.neighbors.KNeighborsClassifier()

In [63]:
knn.fit(iris_X_train, iris_y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [66]:
knn.predict(iris_X_test)

array([1, 0, 0, 0, 2, 2, 0, 0, 0, 2, 2, 0, 1, 0, 2, 2, 2, 0, 2, 2])

In [67]:
knn.predict(iris_X_test) == iris_y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [69]:
from IPython.display import Image

In [70]:
Image(url="https://scikit-learn.org/stable/_images/sphx_glr_plot_iris_0012.png")