In [4]:
import sklearn

In [5]:
from sklearn import datasets

In [6]:
iris = datasets.load_iris()

In [7]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
from sklearn import svm

In [10]:
clasificador = svm.SVC(gamma=0.001, C=100.0)

In [11]:
clasificador.fit(X=iris.data, y=iris.target)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
clasificador.predict(iris.data)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
digits = datasets.load_digits()

In [14]:
clasificador2 = svm.SVC(gamma=0.001, C=100.0)

In [15]:
clasificador2.fit(X=digits.data, y=digits.target)

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
clasificador2.predict(digits.data)

array([0, 1, 2, ..., 8, 9, 8])

In [17]:
import numpy as np

In [18]:
np.sum(clasificador2.predict(digits.data) == digits.target)

1797

In [19]:
np.sum(clasificador2.predict(digits.data) != digits.target)

0

In [20]:
import pickle

In [21]:
open?

In [22]:
#Escribir el modelo
pickle.dump(clasificador2,open('pp', mode='wb'))

In [23]:
ls

AprendizajeSupervisado.Rproj  introduccion.R  knn.R        pp
arbol_de_decision.R           keras.R         mnist_cnn.R  sklearn1.ipynb


In [24]:
! ls -l

total 528
-rw-r--r-- 1 dsc dsc    205 mar  1 18:56 AprendizajeSupervisado.Rproj
-rw-r--r-- 1 dsc dsc    412 mar  1 18:56 arbol_de_decision.R
-rw-r--r-- 1 dsc dsc    699 mar  1 18:56 introduccion.R
-rw-r--r-- 1 dsc dsc   1383 mar  1 18:56 keras.R
-rw-r--r-- 1 dsc dsc    582 mar  1 18:56 knn.R
-rw-r--r-- 1 dsc dsc   1700 mar  1 18:56 mnist_cnn.R
-rw-r--r-- 1 dsc dsc 474363 mar  1 19:17 pp
-rw-r--r-- 1 dsc dsc  37509 mar  1 19:17 sklearn1.ipynb


In [29]:
# cargar el modelo
pickle.load(open("pp", "rb"))

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [30]:
import joblib #otra libreria que hace lo mismo que pickle mas rapida

In [31]:
! pip install joblib

You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [32]:
joblib.dump(clasificador2, "clasificador2")

['clasificador2']

In [33]:
joblib.load( "clasificador2")

SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [34]:
clasificador2.gamma

0.001

## KNN

In [35]:
import numpy as np

In [36]:
iris

{'DESCR': 'Iris Plants Database\n====================\n\nNotes\n-----\nData Set Characteristics:\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)\n    ============== ==== ==== ======= ===== ==

In [37]:
iris.data.shape

(150, 4)

In [38]:
# desordenamos para crear el training y test
np.random.permutation(150)

array([ 33,  60,  92,  77, 145,  74,   4,  47, 138, 112,  51,  26,  81,
        75,  40,  25, 125,  89,  38, 113,  84, 119, 146,  22,  24,  12,
        90, 116,  19,  34, 149,  32, 108,  98,  73, 105,  37,  46,  44,
        79, 135,  76, 100,  57,  10,  72, 136,  16,  66, 137,  13,  69,
       126, 117,  20,  29,  71,   5,  43,  28, 114, 148,  63, 115,  18,
       127, 132,  54,  64, 133, 143,  52,  82,  55,  50, 131,   8,  61,
         9,  49,  94,  59,  62, 147,  80,  83, 134,  58, 144,  39,  41,
        35,   1,  91,  17,  31, 128,  53,  21,   0,  23,  88,  42, 142,
        68, 124, 120,   3, 107, 106, 130, 101, 123,  65, 109,  14, 104,
        45,  96,  70,  48, 102,  27, 111,   6,  99,  30,  86, 110,  97,
        36,   2,  56,  15, 129, 121, 118, 122, 139,  78,  95, 140, 103,
       141,  87,  85,  11,   7,  93,  67])

In [39]:
idx = np.random.permutation(150)

In [40]:
iris_X_train = iris.data[idx[:-20]]
iris_y_train = iris.target[idx[:-20]]
iris_X_test = iris.data[idx[-20:]]
iris_y_test = iris.target[idx[-20:]]

In [41]:
knn = sklearn.neighbors.KNeighborsClassifier()

In [42]:
knn.fit(iris_X_train, iris_y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [43]:
knn.predict(iris_X_test)

array([2, 1, 0, 1, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0])

In [44]:
knn.predict(iris_X_test) == iris_y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [45]:
from IPython.display import Image

In [46]:
Image(url="https://scikit-learn.org/stable/_images/sphx_glr_plot_iris_0012.png")

## Model selection

#### Te busca los hiperparametros mejores para un modelo

In [49]:
#sklearn.model_selection.GridSearchCV
#sklearn.model_selection.RandomizedSearchCV


In [50]:
clasificador2.get_params()

{'C': 100.0,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 0.001,
 'kernel': 'rbf',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

In [51]:
param_grid = [
    {
        "C" : [1, 15, 30, 50, 100, 150, 250, 1000]
    }
]

In [52]:
param_grid

[{'C': [1, 15, 30, 50, 100, 150, 250, 1000]}]

In [59]:
gridSearch = sklearn.model_selection.GridSearchCV(clasificador2, param_grid , cv=5)

In [60]:
gridSearch.fit(digits.data, digits.target)

GridSearchCV(cv=5, error_score='raise',
       estimator=SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'C': [1, 15, 30, 50, 100, 150, 250, 1000]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [61]:
gridSearch.cv_results_

/home/dsc/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/dsc/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/dsc/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/dsc/anaconda3/lib/python3.6/site-pac

{'mean_fit_time': array([0.17261033, 0.16023498, 0.20490484, 0.22008028, 0.16868334,
        0.2000514 , 0.22763538, 0.18248582]),
 'mean_score_time': array([0.04079809, 0.03450103, 0.05246015, 0.04857373, 0.03192544,
        0.05035338, 0.05078773, 0.03321276]),
 'mean_test_score': array([0.97161937, 0.97273233, 0.97273233, 0.97273233, 0.97273233,
        0.97273233, 0.97273233, 0.97273233]),
 'mean_train_score': array([0.99888705, 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        ]),
 'param_C': masked_array(data=[1, 15, 30, 50, 100, 150, 250, 1000],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1},
  {'C': 15},
  {'C': 30},
  {'C': 50},
  {'C': 100},
  {'C': 150},
  {'C': 250},
  {'C': 1000}],
 'rank_test_score': array([8, 1, 1, 1, 1, 1, 1, 1], dtype=int32),
 'split0_test_score': array([0.97527473, 0.97802198, 0.97802198, 0.97802198, 0.97802198

In [62]:
gridSearch.predict(digits.data)

array([0, 1, 2, ..., 8, 9, 8])

In [63]:
param_grid = [
    {
        "C" : [1, 15, 30, 50, 100, 150, 250, 1000],
        "kernel": ["linear"]
    },
    {
        "C" : [1, 10, 100, 500],
        "kernel": ["rbf"]
    }
]

In [64]:
gridSearch2 = sklearn.model_selection.GridSearchCV(clasificador2, param_grid , cv=5)

In [66]:
gridSearch2.fit(digits.data, digits.target)

GridSearchCV(cv=5, error_score='raise',
       estimator=SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'C': [1, 15, 30, 50, 100, 150, 250, 1000], 'kernel': ['linear']}, {'C': [1, 10, 100, 500], 'kernel': ['rbf']}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [68]:
gridSearch2.cv_results_

/home/dsc/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/dsc/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/dsc/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/dsc/anaconda3/lib/python3.6/site-pac

{'mean_fit_time': array([0.05776839, 0.06688247, 0.0721015 , 0.06354518, 0.05019245,
        0.06329751, 0.04272628, 0.04749327, 0.26056323, 0.23917799,
        0.22235098, 0.21541338]),
 'mean_score_time': array([0.01859217, 0.01707578, 0.01505036, 0.02488737, 0.01101232,
        0.01778054, 0.01727772, 0.02277341, 0.06377163, 0.05260324,
        0.05205317, 0.04873528]),
 'mean_test_score': array([0.94936004, 0.94936004, 0.94936004, 0.94936004, 0.94936004,
        0.94936004, 0.94936004, 0.94936004, 0.97161937, 0.97273233,
        0.97273233, 0.97273233]),
 'mean_train_score': array([1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.99888705, 1.        ,
        1.        , 1.        ]),
 'param_C': masked_array(data=[1, 15, 30, 50, 100, 150, 250, 1000, 1, 10, 100, 500],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
           

In [74]:
randomizedSearch = sklearn.model_selection.RandomizedSearchCV(clasificador2, {"C": [1,2,3,4,5,6]} ,n_iter=2)

In [75]:
randomizedSearch.fit(digits.data, y=digits.target)

RandomizedSearchCV(cv=None, error_score='raise',
          estimator=SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
          fit_params=None, iid=True, n_iter=2, n_jobs=1,
          param_distributions={'C': [1, 2, 3, 4, 5, 6]},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0)

## Esquema de validacion o train/test

In [77]:
cancer = sklearn.datasets.load_breast_cancer()

In [76]:
#sklearn.model_selection.KFold
#sklearn.model_selection.train_test_split

In [79]:
X_train, X_test, y_train, y_train = sklearn.model_selection.train_test_split(cancer.data, cancer.target, train_size=0.8)

/home/dsc/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [81]:
X_train.shape

(455, 30)

In [82]:
X_test.shape

(114, 30)

In [84]:
kf = sklearn.model_selection.KFold(4)

In [85]:
kf.get_n_splits()

4

In [87]:
for train, test in kf.split(cancer.data, cancer.target):
    print(train, test)

[143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160
 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178
 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196
 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214
 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232
 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250
 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268
 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286
 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304
 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322
 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340
 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358
 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376
 377 378 379 380 381 382 383 384 385 386 387 388 38

In [89]:
# como vamos a medir la calidad del modelo
sklearn.metrics.accuracy_score(digits.target, clasificador2.predict(digits.data))

1.0

In [90]:
clasificador2.score(digits.data, digits.target)

1.0

In [140]:

for i, (train, test) in enumerate( kf.split(cancer.data, cancer.target)):
    print('division '+str(i))
    # paso 1: dividir en train y test
    X_train = cancer.data[train]
    X_test = cancer.data[test]
    y_train = cancer.target[train]
    y_test = cancer.target[test]
    # paso 2: crear y fitar un model (svm)   
    clasificador = svm.SVC(gamma=0.001, C=100.0)
    clasificador.fit(X=X_train, y=y_train)
    # paso 3: calcular e imprimir el accuracy
    print(sklearn.metrics.accuracy_score(clasificador.predict(X_test), y_test))
    

division 0
0.8811188811188811
division 1
0.9436619718309859
division 2
0.9366197183098591
division 3
0.8732394366197183


In [144]:
from sklearn.datasets import fetch_20newsgroups

In [145]:
text_train = fetch_20newsgroups(subset='train', categories=["sci.med", "comp.graphics"], shuffle=True, random_state=42)

In [146]:
count_vect = sklearn.feature_extraction.text.CountVectorizer()

In [148]:
X_train_counts = count_vect.fit_transform(text_train.data)

In [149]:
count_vect.vocabulary_

{'from': 10161,
 'zyeh': 24608,
 'caspian': 5492,
 'usc': 23190,
 'edu': 8637,
 'zhenghao': 24571,
 'yeh': 24470,
 'subject': 21310,
 're': 18530,
 'need': 15586,
 'polygon': 17527,
 'splitting': 20877,
 'algo': 3261,
 'organization': 16414,
 'university': 23043,
 'of': 16197,
 'southern': 20726,
 'california': 5314,
 'los': 13990,
 'angeles': 3505,
 'ca': 5256,
 'lines': 13813,
 '25': 1072,
 'distribution': 8109,
 'world': 24225,
 'nntp': 15837,
 'posting': 17635,
 'host': 11533,
 'keywords': 13129,
 'polygons': 17530,
 'clipping': 6075,
 'in': 11989,
 'article': 3829,
 '1qvq4b': 833,
 'r4t': 18352,
 'wampyr': 23791,
 'cc': 5545,
 'uow': 23130,
 'au': 4005,
 'g9134255': 10258,
 'coronado': 6832,
 'emmanuel': 8824,
 'abad': 2702,
 'writes': 24275,
 'the': 22081,
 'idea': 11788,
 'is': 12576,
 'to': 22308,
 'clip': 6070,
 'one': 16284,
 'using': 23210,
 'another': 3563,
 'not': 15933,
 'necessarily': 15577,
 'rectangular': 18661,
 'as': 3847,
 'window': 24091,
 'my': 15423,
 'problem': 

In [150]:
tfidf = sklearn.feature_extraction.text.TfidfTransformer()

In [151]:
tfidf.fit_transform(X_train_counts)

<1178x24614 sparse matrix of type '<class 'numpy.float64'>'
	with 170800 stored elements in Compressed Sparse Row format>

## pipelines

In [152]:
from sklearn.pipeline import Pipeline

In [153]:
mi_clasificador = Pipeline([
    ("BoW", sklearn.feature_extraction.text.CountVectorizer()),
    ("tfidf",sklearn.feature_extraction.text.TfidfTransformer() )
])

In [154]:
mi_clasificador.fit(text_train.data, text_train.target)

Pipeline(memory=None,
     steps=[('BoW', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)), ('tfidf', TfidfTransformer(norm='l2', smooth_idf=True, sublinear_tf=False, use_idf=True))])

# https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

Plataformas de cursos:
* Coursera
* edx